# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stu_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_num', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=20)),
                ('student_psd', models.CharField(max_length=20)),
                ('student_sex', models.CharField(max_length=2)),
            ],
        ),
    ]
